#!/usr/bin/env python3
# ==============================================================================
# B:Essential Agentic Harness v4.0 - frontmatter_backfill.py
# ==============================================================================
# 목적: Urban_vault 내 frontmatter가 전혀 없는 레거시 md 파일에 스키마 최소
#       frontmatter(필수 7키)를 주입합니다. 기존 본문은 절대 수정하지 않습니다.
# 범위: vault_linter.py W1과 동일 (Raw Sources/Archive/Inbox/_Templates 등 제외)
# 사용: python3 frontmatter_backfill.py [--apply]   (기본은 dry-run)
# ==============================================================================

import sys
from datetime import date, datetime
from pathlib import Path

VAULT_NAME = "vault"  # AX_Infra
SKIP_PARTS = {".obsidian", ".smart-env", ".trash", "_Templates", "04. Archive",
              "00. Inbox", "Raw Sources", "TaskNotes", "Clippings", "codexx", ".auth"}
SKIP_FILES = {"log.md"}


def make_frontmatter(p: Path) -> str:
    mtime = date.fromtimestamp(p.stat().st_mtime).isoformat()
    today = date.today().isoformat()
    stem = p.stem.replace('"', "'")
    return (
        "---\n"
        "type: query-result\n"
        "aliases:\n"
        f"  - \"{stem}\"\n"
        "description: \"Backfilled minimal frontmatter for a legacy project artifact. "
        "Auto-generated by frontmatter_backfill.py; body content untouched.\"\n"
        "author:\n"
        "  - backfill\n"
        f"date created: {mtime}\n"
        f"date modified: {today}\n"
        "tags:\n"
        "  - backfill\n"
        "  - legacy\n"
        "---\n\n"
    )


def main() -> None:
    apply = "--apply" in sys.argv
    project_root = Path(__file__).resolve().parents[2]
    vault = project_root / VAULT_NAME
    targets = []
    for p in vault.rglob("*.md"):
        rel = p.relative_to(vault)
        if any(part in SKIP_PARTS for part in rel.parts) or p.name in SKIP_FILES:
            continue
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if not text.lstrip("﻿\n\r ").startswith("---"):
            targets.append(p)

    mode = "APPLY" if apply else "DRY-RUN"
    print(f"🔧 [Backfill/{mode}] frontmatter 없는 파일 {len(targets)}건")
    for p in targets:
        print(f"   - {p.relative_to(vault)}")
        if apply:
            original = p.read_text(encoding="utf-8", errors="replace")
            p.write_text(make_frontmatter(p) + original, encoding="utf-8")
    if apply:
        print(f"✅ [Backfill] {len(targets)}건 주입 완료. vault_linter.py로 재검증하세요.")
    else:
        print("ℹ️  실제 적용: python3 frontmatter_backfill.py --apply")


if __name__ == "__main__":
    main()
